// Fetch weather
export const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_ERROR = 'FETCH_WEATHER_ERROR';
// Save/Remove city favs
export const FAVOURITE_CITY_ADD = 'FAVOURITE_CITY_ADD';
export const FAVOURITE_CITY_REMOVE = 'FAVOURITE_CITY_REMOVE';